name: CI/CD Loja Veloz

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Análise de Código (Lint com flake8)
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Instalar Dependências
      run: |
        pip install -r servico-pedidos/requirements.txt
        pip install -r api-gateway/requirements.txt
        pip install pytest

    - name: Rodar Testes Unitários (Simulação)
      run: |
        python -m compileall .

    - name: Demonstracao de Secrets no Pipeline
      run: echo "Simulando injeção segura de credenciais para o Registry..."
      env:
        MEU_TOKEN_SECRETO: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build e Push da Imagem - Pedidos
      uses: docker/build-push-action@v4
      with:
        context: ./servico-pedidos
        push: false
        tags: guilherme/servico-pedidos:latest

    - name: Build e Push da Imagem - Gateway
      uses: docker/build-push-action@v4
      with:
        context: ./api-gateway
        push: false
        tags: guilherme/api-gateway:latest
